[[headers]]
  for = "/rss.xml"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[build]
  publish = "public"
  command = "npm run netlify"
  functions = "public/functions/"

[build.environment]
  YARN_VERSION = "1.22.4"
  NODE_VERSION = "12.16.3"